### PR TITLE
lending: add `AdjustObligationCollateral` instruction

### PR DESCRIPTION
**Pull request by jordansexton**
WIP

### CODE REVIEW

**Comment by jordansexton** [comment]
A general impression -- the implementation seems like it could be simpler and have a more obvious API with two instructions (e.g. `DepositObligationCollateral` and `WithdrawObligationCollateral`) instead of one.

**Comment by joncinque** [comment]
This is going in a great direction.

One thing to add are the obligation token account and mint.  On a borrow, obligation tokens are minted 1:1 with collateral tokens, as a proof of ownership of the obligation.  When adjusting collateral, we also need to mint / burn the right amount of obligation tokens.

Regarding splitting the instruction, that seems reasonable  Since adding collateral can never make a loan less healthy, we can disable a lot of checks and simplify it. @jstarry did you have a reason for keeping it as one instruction?

**Comment by bartosz-lipinski** [comment]
@jordansexton this is a great start. Can you please open a draft PR to the main repo.

**Comment by jordansexton** [comment]
Thanks for the feedback! Will continue @ https://github.com/solana-labs/solana-program-library/pull/1229

**Pull request closed without merging**
